"use client";

import { BlurFade, Button, buttonVariants, Card, CardContent, cn } from "@allsource/ui";
import {
  AlertTriangle,
  ArrowRight,
  Check,
  Copy,
  Download,
  ExternalLink,
  Loader2,
  Terminal,
} from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { apiClient } from "@/lib/api/client";

// The scopes Prime needs for `--sync-to`: it POSTs prime.* events to
// /api/v1/events on the remote Core. events:read is included so the
// same key works for inspection/debugging from the dashboard or SDKs.
const PRIME_SCOPES = ["events:write", "events:read"] as const;
const KEY_NAME = "Claude Desktop (Prime)";
const SYNC_TO_URL = "https://api.all-source.xyz";

type SessionState =
  | { status: "loading" }
  | { status: "unauthenticated" }
  | { status: "authenticated" };

type KeyState =
  | { status: "idle" }
  | { status: "creating" }
  | { status: "ready"; key: string }
  | { status: "error"; message: string };

export function ConnectClient() {
  const [session, setSession] = useState<SessionState>({ status: "loading" });
  const [key, setKey] = useState<KeyState>({ status: "idle" });

  // Deep-link contract (bead t-baff / gap 3):
  // - source — tags the minted API key's description so the maintainer
  //   can tell where keys came from in /dashboard/api-keys (e.g. an agent
  //   walking a human through the article vs a hand-mint via the dashboard).
  // - key_name — overrides the default KEY_NAME ("Claude Desktop (Prime)")
  //   so a human (or agent) can identify multiple keys by machine.
  // - return=close — switches the post-mint UI to a "you can close this tab"
  //   state for visitors driven here by an out-of-band agent flow; default
  //   behavior (no param) still shows the manage-keys link for visitors
  //   who came on their own and want to stay on the dashboard.
  const params = useSearchParams();
  const sourceParam = params.get("source")?.trim() || null;
  const keyNameParam = params.get("key_name")?.trim() || null;
  const closeAfterMint = params.get("return") === "close";

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/auth/session", { credentials: "include" });
        if (cancelled) return;
        if (!res.ok) {
          setSession({ status: "unauthenticated" });
          return;
        }
        const body = await res.json();
        setSession({
          status: body?.data?.user ? "authenticated" : "unauthenticated",
        });
      } catch {
        if (!cancelled) setSession({ status: "unauthenticated" });
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const handleCreate = async () => {
    setKey({ status: "creating" });
    // If `?source=` is set, splice it into the description so it shows up in
    // /dashboard/api-keys. Falls back to the original copy when no source.
    const description = sourceParam
      ? `Generated by /connect for Claude Desktop Prime sync (source: ${sourceParam}).`
      : "Generated by /connect for Claude Desktop Prime sync.";
    const name = keyNameParam ?? KEY_NAME;
    const res = await apiClient.createApiKey({
      name,
      description,
      scopes: [...PRIME_SCOPES],
    });
    if (res.error) {
      setKey({ status: "error", message: res.error.message });
      return;
    }
    if (!res.data?.key) {
      setKey({
        status: "error",
        message: "API responded without a key value — try again from /dashboard/api-keys.",
      });
      return;
    }
    setKey({ status: "ready", key: res.data.key });
  };

  return (
    <>
      <BlurFade delay={0.1} inView>
        <h1 className="text-3xl font-bold text-foreground sm:text-4xl mb-2">
          Connect to Claude Desktop
        </h1>
        <p className="text-lg text-muted-foreground">
          One click mints an API key scoped for Prime sync and renders a ready-to-paste config
          snippet for Claude Desktop. No checklist back-and-forth with the model.
        </p>
      </BlurFade>

      <div className="mt-10 space-y-6">
        {session.status === "loading" && (
          <Card>
            <CardContent className="flex items-center gap-3 py-6 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              Checking your session…
            </CardContent>
          </Card>
        )}

        {session.status === "unauthenticated" && <UnauthenticatedCard />}

        {session.status === "authenticated" && key.status !== "ready" && (
          <CreateKeyCard state={key} onCreate={handleCreate} />
        )}

        {key.status === "ready" && <ReadyState apiKey={key.key} closeAfterMint={closeAfterMint} />}
      </div>
    </>
  );
}

function UnauthenticatedCard() {
  return (
    <Card>
      <CardContent className="space-y-4 py-6">
        <p className="text-sm text-muted-foreground">
          You need an AllSource account before you can mint a Claude Desktop key. The free tier is
          enough to follow the blog post end-to-end.
        </p>
        <div className="flex flex-wrap gap-2">
          <Link href="/signup?next=/connect" className={cn(buttonVariants(), "gap-1.5")}>
            Create free account
            <ArrowRight className="h-4 w-4" />
          </Link>
          <Link href="/login?next=/connect" className={cn(buttonVariants({ variant: "outline" }))}>
            Sign in
          </Link>
        </div>
        <p className="text-xs text-muted-foreground">
          Signing in with Google or GitHub? After auth, navigate back to{" "}
          <code className="font-mono">/connect</code> manually — the OAuth round-trip drops the
          return path.
        </p>
      </CardContent>
    </Card>
  );
}

function CreateKeyCard({
  state,
  onCreate,
}: {
  state: Exclude<KeyState, { status: "ready" }>;
  onCreate: () => void;
}) {
  return (
    <Card>
      <CardContent className="space-y-4 py-6">
        <div>
          <h2 className="text-lg font-semibold">Create Claude Desktop key</h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Creates an API key named <code className="font-mono text-xs">{KEY_NAME}</code> with
            scopes <code className="font-mono text-xs">{PRIME_SCOPES.join(", ")}</code>. You can
            rotate or revoke it any time from{" "}
            <Link className="underline" href="/dashboard/api-keys">
              /dashboard/api-keys
            </Link>
            .
          </p>
        </div>

        {state.status === "error" && (
          <div className="flex items-start gap-2 rounded-md border border-destructive/40 bg-destructive/10 p-3">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-destructive" />
            <p className="text-sm text-destructive">{state.message}</p>
          </div>
        )}

        <Button onClick={onCreate} disabled={state.status === "creating"} className="gap-1.5">
          {state.status === "creating" ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Minting key…
            </>
          ) : (
            <>
              Create connection
              <ArrowRight className="h-4 w-4" />
            </>
          )}
        </Button>
      </CardContent>
    </Card>
  );
}

function ReadyState({ apiKey, closeAfterMint }: { apiKey: string; closeAfterMint: boolean }) {
  const configSnippet = useMemo(() => buildClaudeDesktopConfig(apiKey), [apiKey]);
  const installCmd = `curl -fsSL https://www.all-source.xyz/install.sh | ALLSOURCE_API_KEY='${apiKey}' sh`;

  return (
    <div className="space-y-6">
      {closeAfterMint && (
        // Agent-driven flow: the human was sent here by an out-of-band
        // assistant (Claude Desktop, etc.) that's waiting on the key.
        // Tell them explicitly to copy + close + return — the rest of
        // this page is reference material they don't need.
        <Card className="border-primary/40 bg-primary/5">
          <CardContent className="flex items-start gap-3 py-4 text-sm">
            <Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
            <div>
              <span className="font-medium">Key ready.</span> Copy it (button below), close this
              tab, and paste it back into the assistant that sent you here. The install options
              below are for reference — your assistant has the steps.
            </div>
          </CardContent>
        </Card>
      )}

      <Card className="border-yellow-500/40 bg-yellow-500/5">
        <CardContent className="flex items-start gap-3 py-4 text-sm">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-yellow-600" />
          <div className="text-yellow-700 dark:text-yellow-400">
            <span className="font-medium">Save this key now.</span> We don't show secrets twice. If
            you lose it, rotate from{" "}
            <Link className="underline" href="/dashboard/api-keys">
              /dashboard/api-keys
            </Link>
            .
          </div>
        </CardContent>
      </Card>

      <section>
        <h2 className="mb-2 flex items-center gap-2 text-lg font-semibold">
          <Download className="h-4 w-4" />
          Option A — Claude Desktop Extension (recommended)
        </h2>
        <p className="mb-3 text-sm text-muted-foreground">
          Download the <code className="font-mono text-xs">.dxt</code> bundle and double-click it.
          Claude Desktop installs it natively, prompts for your API key (paste below), and writes
          the config for you. No terminal. macOS (Apple Silicon) and Linux x86_64.
        </p>
        <div className="flex flex-wrap gap-2">
          <Link
            href="https://github.com/all-source-os/all-source/releases/latest/download/allsource-prime.dxt"
            className={cn(buttonVariants(), "gap-1.5")}
          >
            <Download className="h-4 w-4" />
            Download allsource-prime.dxt
          </Link>
          <Link
            href="https://github.com/all-source-os/all-source/releases/latest"
            className={cn(buttonVariants({ variant: "ghost" }), "gap-1.5 text-sm")}
          >
            All assets
            <ExternalLink className="h-3.5 w-3.5" />
          </Link>
        </div>
      </section>

      <section>
        <h2 className="mb-2 flex items-center gap-2 text-lg font-semibold">
          <Terminal className="h-4 w-4" />
          Option B — one-line installer (macOS, Linux)
        </h2>
        <p className="mb-3 text-sm text-muted-foreground">
          Downloads the <code className="font-mono text-xs">allsource-prime</code> binary, writes
          the Claude Desktop config (preserving any existing MCP servers), and prints next steps.
        </p>
        <CopyBlock content={installCmd} language="bash" />
      </section>

      <section>
        <h2 className="mb-2 flex items-center gap-2 text-lg font-semibold">
          <Download className="h-4 w-4" />
          Option C — paste the config yourself
        </h2>
        <p className="mb-3 text-sm text-muted-foreground">
          Open Claude Desktop's config file and merge the snippet below into{" "}
          <code className="font-mono text-xs">mcpServers</code>. After saving, install the binary (
          <code className="font-mono text-xs">cargo install allsource-prime</code>) and restart
          Claude Desktop.
        </p>
        <ConfigPathHint />
        <CopyBlock content={configSnippet} language="json" />
      </section>

      <section>
        <h2 className="mb-2 text-lg font-semibold">After install</h2>
        <ul className="ml-5 list-disc space-y-1.5 text-sm text-muted-foreground">
          <li>Restart Claude Desktop so it picks up the new MCP server.</li>
          <li>
            Verify by asking Claude: <em>"List the MCP tools you have available."</em> You should
            see <code className="font-mono text-xs">prime_add_node</code>,{" "}
            <code className="font-mono text-xs">prime_recall</code>, and friends.
          </li>
          <li>
            Watch nodes appear live at{" "}
            <Link className="underline" href="/dashboard/memory">
              /dashboard/memory
            </Link>
            .
          </li>
        </ul>
      </section>

      <div className="flex flex-wrap gap-2">
        <Link
          href="/dashboard/api-keys"
          className={cn(buttonVariants({ variant: "outline" }), "gap-1.5")}
        >
          Manage keys
          <ExternalLink className="h-3.5 w-3.5" />
        </Link>
        <Link href="/docs/prime/mcp" className={cn(buttonVariants({ variant: "ghost" }))}>
          MCP docs
        </Link>
      </div>
    </div>
  );
}

function ConfigPathHint() {
  return (
    <div className="mb-3 rounded-md border bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
      <span className="font-medium text-foreground">Config file path:</span>{" "}
      <span className="font-mono">
        ~/Library/Application Support/Claude/claude_desktop_config.json
      </span>{" "}
      (macOS) · <span className="font-mono">~/.config/Claude/claude_desktop_config.json</span>{" "}
      (Linux) · <span className="font-mono">%APPDATA%\Claude\claude_desktop_config.json</span>{" "}
      (Windows)
    </div>
  );
}

function CopyBlock({ content, language }: { content: string; language: "bash" | "json" }) {
  const [copied, setCopied] = useState(false);
  const onCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };
  return (
    <div className="relative">
      <pre className="overflow-x-auto rounded-md border bg-muted/30 p-4 text-xs">
        <code className={`language-${language} font-mono`}>{content}</code>
      </pre>
      <Button
        type="button"
        size="sm"
        variant="outline"
        className="absolute right-2 top-2 h-7 gap-1 px-2 text-xs"
        onClick={onCopy}
      >
        {copied ? (
          <>
            <Check className="h-3 w-3" />
            Copied
          </>
        ) : (
          <>
            <Copy className="h-3 w-3" />
            Copy
          </>
        )}
      </Button>
    </div>
  );
}

function buildClaudeDesktopConfig(apiKey: string): string {
  return JSON.stringify(
    {
      mcpServers: {
        prime: {
          command: "allsource-prime",
          args: [
            "--data-dir",
            "~/.prime/memory",
            "--auto-inject",
            "--sync-to",
            SYNC_TO_URL,
            "--api-key",
            apiKey,
          ],
        },
      },
    },
    null,
    2
  );
}
