package usecases

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/allsource/control-plane/internal/application/dto"
	"github.com/allsource/control-plane/internal/domain/entities"
	"github.com/allsource/control-plane/internal/domain/repositories"
	"github.com/allsource/control-plane/internal/infrastructure/clients"
)

const (
	agentFreeTierEventsQuota  = 10000
	agentFreeTierQueriesQuota = 1000
)

// RegisterAgentUseCase handles agent self-registration.
// Creates a tenant with agent metadata and returns an API key.
type RegisterAgentUseCase struct {
	createTenantUC *CreateTenantUseCase
	auditRepo      repositories.AuditRepository
	coreClient     clients.CoreClient
}

// NewRegisterAgentUseCase creates a new RegisterAgentUseCase.
func NewRegisterAgentUseCase(
	createTenantUC *CreateTenantUseCase,
	auditRepo repositories.AuditRepository,
	coreClient clients.CoreClient,
) *RegisterAgentUseCase {
	return &RegisterAgentUseCase{
		createTenantUC: createTenantUC,
		auditRepo:      auditRepo,
		coreClient:     coreClient,
	}
}

// Execute registers a new agent, creating a tenant and returning an API key.
// The API key is generated by the caller (handler) since it requires JWT signing
// with the server's secret — the use case returns the tenant response.
func (uc *RegisterAgentUseCase) Execute(ctx context.Context, req dto.RegisterAgentRequest) (*dto.TenantResponse, error) {
	// Generate deterministic tenant ID from agent name
	slug := strings.ToLower(req.AgentName)
	slug = strings.ReplaceAll(slug, " ", "-")
	tenantID := fmt.Sprintf("agent-%s", slug)

	// Create tenant with agent metadata
	tenantResp, err := uc.createTenantUC.Execute(dto.CreateTenantRequest{
		ID:          tenantID,
		Name:        req.AgentName,
		Description: fmt.Sprintf("Agent tenant for %s (%s)", req.AgentName, req.AgentType),
		Metadata: map[string]interface{}{
			"agent_type": req.AgentType,
			"subscription": map[string]interface{}{
				"tier":   "free",
				"status": "active",
			},
			"quota": map[string]interface{}{
				"events_quota":  agentFreeTierEventsQuota,
				"queries_quota": agentFreeTierQueriesQuota,
			},
		},
	})
	if err != nil {
		return nil, err
	}

	// Write agent.registered event to Core (non-blocking)
	uc.writeRegisteredEvent(ctx, tenantID, req)

	// Audit log
	auditEvent, _ := entities.NewAuditEvent("agent.registered", "create", "POST", "/agents/register") //nolint:errcheck
	auditEvent.WithResource("agent", tenantID).WithTenant(tenantID)
	auditEvent.AddMetadata("agent_type", req.AgentType)
	_ = uc.auditRepo.Log(auditEvent) //nolint:errcheck

	return tenantResp, nil
}

// writeRegisteredEvent writes an agent.registered event to Core for audit trail.
func (uc *RegisterAgentUseCase) writeRegisteredEvent(ctx context.Context, tenantID string, req dto.RegisterAgentRequest) {
	if uc.coreClient == nil {
		return
	}

	_, err := uc.coreClient.IngestEvent(ctx, clients.IngestEventRequest{
		EventType: "agent.registered",
		EntityID:  tenantID,
		Payload: map[string]any{
			"agent_name":    req.AgentName,
			"agent_type":    req.AgentType,
			"tier":          "free",
			"events_quota":  agentFreeTierEventsQuota,
			"queries_quota": agentFreeTierQueriesQuota,
		},
	})
	if err != nil {
		log.Printf("[agent] failed to write agent.registered event for %s: %v", tenantID, err)
	}
}
