apiVersion: v2
name: allsource
description: High-performance event sourcing platform with Rust Core and Elixir Query Service
type: application
version: 0.6.0
appVersion: "0.6.0"

keywords:
  - event-sourcing
  - event-store
  - cqrs
  - rust
  - elixir

maintainers:
  - name: AllSource Team
    url: https://github.com/all-source-os/allsource-monorepo

home: https://github.com/all-source-os/allsource-monorepo
sources:
  - https://github.com/all-source-os/allsource-monorepo

dependencies: []
